include:
  - board: xiao_ble/nrf52840/sense
    shield: forager_left
    cmake-args: -DZMK_CONFIG=config/keyboard

  - board: xiao_ble/nrf52840/sense
    shield: forager_right
    cmake-args: -DZMK_CONFIG=config/keyboard

  - board: xiao_ble/nrf52840/sense
    shield: forager_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DZMK_CONFIG=config/dongle
